
export const GET_ADDRESS = 'get_address'
export const GET_SWIPERSHOPS = 'get_swipershops'
export const GET_BUSINESSLIST = 'get_businesslist'
export const GET_SHOPDATA = 'get_shopdata'
export const GET_SHOPIFO = 'get_shopifo'
export const GET_SHOPNAV = 'get_shopnav'
export const ADD_COLLECTNUM = 'add_collectnum'
export const DEL_COLLECTNUM = 'del_collectnum'
export const DEL_ALLSHOPFOOD = 'del_allshopfood'
export const SAVE_CARTLOCATION = 'save_cartlocation'
export const SAVE_CARTSHOP = 'save_cartshop'